{
  "timestamp": "2025-06-11T03:14:20.748564",
  "results": {
    "Geoid Creation Stress Test": {
      "total_geoids": 300,
      "successful": 300,
      "failed": 0,
      "total_time": 6.27,
      "requests_per_second": 47.83,
      "avg_response_time": 0.1575,
      "max_response_time": 5.415,
      "min_response_time": 0.0135
    },
    "Contradiction Processing Stress Test": {
      "total_tests": 50,
      "successful": 50,
      "failed": 0,
      "total_time": 83.44,
      "contradictions_found": 1076,
      "scars_created": 1076,
      "avg_time_per_test": 1.6688
    },
    "Cognitive Cycle Stress Test": {
      "total_cycles": 25,
      "successful": 2,
      "failed": 23,
      "total_time": 25157.65,
      "avg_cycle_time": 3664.5649,
      "max_cycle_time": 4382.4382,
      "min_cycle_time": 2946.6916
    },
    "Vault Operations Stress Test": {
      "total_operations": 100,
      "successful": 0,
      "failed": 100,
      "total_time": 299.17,
      "operations_per_second": 0.33
    },
    "System Status Query Stress Test": {
      "total_queries": 500,
      "successful": 500,
      "failed": 0,
      "total_time": 7.39,
      "queries_per_second": 67.64,
      "avg_response_time": 0.2202,
      "max_response_time": 0.3174
    },
    "Memory Stress Test": {
      "duration": 38.95,
      "total_operations": 4,
      "operations_per_second": 0.1
    }
  },
  "errors": [
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_41f1b67a', '[\"GEOID_30e32539\", \"GEOID_2963c662\"]', 'auto-cycle', '2025-06-11 03:15:07.126587', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 03:15:07.130853', '[0.4117647058823529, 0.6627450980392157, 0.5058823529411764, 0.5450980392156862, 0.16862745098039217, 0.12156862745098039, 0.6980392156862745, 0.1333 ... (7442 characters truncated) ... 980392155, 0.5843137254901961, 0.1803921568627451, 0.6196078431372549, 0.6470588235294118, 0.9411764705882353, 0.9686274509803922, 0.792156862745098]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_aed0bbd6', '[\"GEOID_def88039\", \"GEOID_13fad4d6\"]', 'auto-cycle', '2025-06-11 04:20:12.130004', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 04:20:12.143000', '[0.00392156862745098, 0.8862745098039215, 0.6588235294117647, 0.7058823529411765, 0.47843137254901963, 0.5411764705882353, 0.27058823529411763, 0.431 ... (7322 characters truncated) ... , 0.20784313725490197, 0.07058823529411765, 0.47843137254901963, 0.4, 0.8156862745098039, 0.3843137254901961, 0.4823529411764706, 0.5882352941176471]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_c644f8f5', '[\"GEOID_bb3c1b00\", \"GEOID_93001007\"]', 'auto-cycle', '2025-06-11 04:57:21.620062', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 04:57:21.654227', '[0.5568627450980392, 0.6705882352941176, 0.8862745098039215, 0.8117647058823529, 0.42745098039215684, 0.5019607843137255, 0.7686274509803922, 0.89411 ... (7550 characters truncated) ... 08, 0.33725490196078434, 0.09019607843137255, 0.01568627450980392, 0.10196078431372549, 0.45098039215686275, 0.9686274509803922, 0.39215686274509803]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_4a6b6614', '[\"GEOID_9163e15f\", \"GEOID_5e99b404\"]', 'auto-cycle', '2025-06-11 05:13:22.067101', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 05:13:22.117092', '[0.9058823529411765, 0.1411764705882353, 0.5803921568627451, 0.6745098039215687, 0.3137254901960784, 0.396078431372549, 0.5529411764705883, 0.3176470 ... (7478 characters truncated) ... 4116, 0.12549019607843137, 0.6549019607843137, 0.19607843137254902, 0.24313725490196078, 0.6078431372549019, 0.30980392156862746, 0.6901960784313725]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_161dc88e', '[\"GEOID_a49bed61\", \"GEOID_205007ee\"]', 'auto-cycle', '2025-06-11 06:35:28.349683', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 06:35:28.382437', '[0.9098039215686274, 0.6313725490196078, 0.4745098039215686, 0.39215686274509803, 0.49411764705882355, 0.44313725490196076, 0.0, 0.5568627450980392,  ... (7166 characters truncated) ... 509804, 0.5215686274509804, 0.01568627450980392, 0.42745098039215684, 0.9921568627450981, 0.9333333333333333, 0.4549019607843137, 0.7294117647058823]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_d7052143', '[\"GEOID_565fb3b0\", \"GEOID_ff29f3f4\"]', 'auto-cycle', '2025-06-11 06:51:11.604769', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 06:51:11.636636', '[0.8862745098039215, 0.9803921568627451, 0.9607843137254902, 0.3137254901960784, 0.9882352941176471, 0.7803921568627451, 0.5176470588235295, 0.337254 ... (7106 characters truncated) ... 76, 0.5686274509803921, 0.7019607843137254, 0.7647058823529411, 0.6, 0.48627450980392156, 0.5019607843137255, 0.25098039215686274, 0.788235294117647]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_16e821a2', '[\"GEOID_8f8345e3\", \"GEOID_85daeadb\"]', 'auto-cycle', '2025-06-11 06:52:21.425909', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 06:52:21.458170', '[0.08235294117647059, 0.6666666666666666, 0.25882352941176473, 0.043137254901960784, 0.12941176470588237, 0.7215686274509804, 0.5450980392156862, 0.2 ... (7538 characters truncated) ... 54902, 0.7764705882352941, 0.8823529411764706, 0.058823529411764705, 0.00392156862745098, 0.5568627450980392, 0.9411764705882353, 0.2901960784313726]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_c2a049d4', '[\"GEOID_7ccb0fd7\", \"GEOID_5e99b404\"]', 'auto-cycle', '2025-06-11 07:02:23.564008', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 07:02:23.598334', '[0.047058823529411764, 0.49411764705882355, 0.1411764705882353, 0.15294117647058825, 0.4117647058823529, 0.3764705882352941, 0.10196078431372549, 0.3 ... (7322 characters truncated) ... 01960785, 0.7137254901960784, 0.6274509803921569, 0.7568627450980392, 0.6745098039215687, 0.5568627450980392, 0.7490196078431373, 0.8549019607843137]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_29e2f454', '[\"GEOID_e758a36b\", \"GEOID_38e3f8e2\"]', 'auto-cycle', '2025-06-11 07:02:47.413350', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 07:02:47.472054', '[0.984313725490196, 0.08235294117647059, 0.7843137254901961, 0.5058823529411764, 0.13333333333333333, 0.1450980392156863, 0.3803921568627451, 0.26666 ... (7382 characters truncated) ... 96078, 0.7058823529411765, 0.9294117647058824, 0.8117647058823529, 0.6392156862745098, 0.38823529411764707, 0.23529411764705882, 0.14901960784313725]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_18f75c34', '[\"GEOID_5d034e82\", \"GEOID_2f20ab32\"]', 'auto-cycle', '2025-06-11 07:31:24.836697', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 07:31:24.873770', '[0.2627450980392157, 0.7647058823529411, 0.28627450980392155, 0.25098039215686274, 0.03529411764705882, 0.8784313725490196, 0.43529411764705883, 0.41 ... (7586 characters truncated) ... 254, 0.11372549019607843, 0.09019607843137255, 0.06274509803921569, 0.6901960784313725, 0.9725490196078431, 0.6352941176470588, 0.027450980392156862]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_e1886199', '[\"GEOID_38e3f8e2\", \"GEOID_c35c0175\"]', 'auto-cycle', '2025-06-11 07:39:50.455367', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 07:39:50.490916', '[0.6196078431372549, 0.1450980392156863, 0.29411764705882354, 0.9372549019607843, 0.5450980392156862, 0.03137254901960784, 0.3568627450980392, 0.4784 ... (7358 characters truncated) ... 5686275, 0.4627450980392157, 0.6705882352941176, 0.3333333333333333, 0.6941176470588235, 0.27058823529411763, 0.0196078431372549, 0.8941176470588236]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_6153e0d8', '[\"GEOID_e9135de5\", \"GEOID_946d84e3\"]', 'auto-cycle', '2025-06-11 07:41:50.706433', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 07:41:50.743800', '[0.48627450980392156, 0.10196078431372549, 0.6705882352941176, 0.9647058823529412, 0.5725490196078431, 0.00784313725490196, 0.5411764705882353, 0.533 ... (7526 characters truncated) ... 0392156, 0.5176470588235295, 0.8784313725490196, 0.043137254901960784, 0.7019607843137254, 0.6274509803921569, 0.1607843137254902, 0.788235294117647]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_64087e33', '[\"GEOID_70dafe6b\", \"GEOID_9e0a4264\"]', 'auto-cycle', '2025-06-11 08:19:11.563193', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 08:19:11.625368', '[0.7372549019607844, 0.7058823529411765, 0.8, 0.08627450980392157, 0.3607843137254902, 0.4235294117647059, 0.2784313725490196, 0.3333333333333333, 0. ... (7250 characters truncated) ... 5294116, 0.792156862745098, 0.6392156862745098, 0.08235294117647059, 0.24705882352941178, 0.6823529411764706, 0.5490196078431373, 0.7176470588235294]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_ceaf345e', '[\"GEOID_996b58b2\", \"GEOID_a239710c\"]', 'auto-cycle', '2025-06-11 08:46:27.652415', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 08:46:27.692690', '[0.5019607843137255, 0.7215686274509804, 0.8862745098039215, 0.5411764705882353, 0.9568627450980393, 0.9411764705882353, 0.7333333333333333, 0.913725 ... (7478 characters truncated) ... 078432, 0.9333333333333333, 0.43137254901960786, 0.39215686274509803, 0.6627450980392157, 0.803921568627451, 0.9098039215686274, 0.08627450980392157]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_30d6450c', '[\"GEOID_e758a36b\", \"GEOID_2f9d2209\"]', 'auto-cycle', '2025-06-11 08:47:14.124471', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 08:47:14.167655', '[0.7215686274509804, 0.10196078431372549, 0.12156862745098039, 0.996078431372549, 0.7058823529411765, 0.20784313725490197, 0.9921568627450981, 0.8784 ... (7358 characters truncated) ... 0.25098039215686274, 0.4235294117647059, 0.054901960784313725, 0.3764705882352941, 0.15294117647058825, 0.8, 0.33725490196078434, 0.4823529411764706]', 'vault_b')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_33a8b21c', '[\"GEOID_3b19edf1\", \"GEOID_703c45c2\"]', 'auto-cycle', '2025-06-11 09:48:27.656558', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 150.0, 0.0, 0.8333333333333334, 1.0, '2025-06-11 09:48:27.725236', '[0.3058823529411765, 0.37254901960784315, 0.19607843137254902, 0.9215686274509803, 0.9058823529411765, 0.9882352941176471, 0.5058823529411764, 0.4784 ... (7466 characters truncated) ... 84313725, 0.6196078431372549, 0.17647058823529413, 0.7058823529411765, 0.6980392156862745, 0.803921568627451, 0.9607843137254902, 0.6431372549019608]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.OperationalError) database is locked\n(Background on this error at: https://sqlalche.me/e/20/e3q8)",
    "cognitive_cycle: (sqlite3.OperationalError) database is locked\n[SQL: SELECT count(*) AS count_1 \nFROM (SELECT scars.scar_id AS scars_scar_id, scars.geoids AS scars_geoids, scars.reason AS scars_reason, scars.timestamp AS scars_timestamp, scars.resolved_by AS scars_resolved_by, scars.pre_entropy AS scars_pre_entropy, scars.post_entropy AS scars_post_entropy, scars.delta_entropy AS scars_delta_entropy, scars.cls_angle AS scars_cls_angle, scars.semantic_polarity AS scars_semantic_polarity, scars.mutation_frequency AS scars_mutation_frequency, scars.weight AS scars_weight, scars.last_accessed AS scars_last_accessed, scars.scar_vector AS scars_scar_vector, scars.vault_id AS scars_vault_id \nFROM scars \nWHERE scars.vault_id = ?) AS anon_1]\n[parameters: ('vault_a',)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)",
    "cognitive_cycle: (sqlite3.OperationalError) database is locked\n[SQL: SELECT count(*) AS count_1 \nFROM (SELECT scars.scar_id AS scars_scar_id, scars.geoids AS scars_geoids, scars.reason AS scars_reason, scars.timestamp AS scars_timestamp, scars.resolved_by AS scars_resolved_by, scars.pre_entropy AS scars_pre_entropy, scars.post_entropy AS scars_post_entropy, scars.delta_entropy AS scars_delta_entropy, scars.cls_angle AS scars_cls_angle, scars.semantic_polarity AS scars_semantic_polarity, scars.mutation_frequency AS scars_mutation_frequency, scars.weight AS scars_weight, scars.last_accessed AS scars_last_accessed, scars.scar_vector AS scars_scar_vector, scars.vault_id AS scars_vault_id \nFROM scars \nWHERE scars.vault_id = ?) AS anon_1]\n[parameters: ('vault_a',)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)",
    "cognitive_cycle: (sqlite3.OperationalError) database is locked\n[SQL: SELECT count(*) AS count_1 \nFROM (SELECT scars.scar_id AS scars_scar_id, scars.geoids AS scars_geoids, scars.reason AS scars_reason, scars.timestamp AS scars_timestamp, scars.resolved_by AS scars_resolved_by, scars.pre_entropy AS scars_pre_entropy, scars.post_entropy AS scars_post_entropy, scars.delta_entropy AS scars_delta_entropy, scars.cls_angle AS scars_cls_angle, scars.semantic_polarity AS scars_semantic_polarity, scars.mutation_frequency AS scars_mutation_frequency, scars.weight AS scars_weight, scars.last_accessed AS scars_last_accessed, scars.scar_vector AS scars_scar_vector, scars.vault_id AS scars_vault_id \nFROM scars \nWHERE scars.vault_id = ?) AS anon_1]\n[parameters: ('vault_a',)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)",
    "cognitive_cycle: (sqlite3.OperationalError) database is locked\n[SQL: SELECT count(*) AS count_1 \nFROM (SELECT scars.scar_id AS scars_scar_id, scars.geoids AS scars_geoids, scars.reason AS scars_reason, scars.timestamp AS scars_timestamp, scars.resolved_by AS scars_resolved_by, scars.pre_entropy AS scars_pre_entropy, scars.post_entropy AS scars_post_entropy, scars.delta_entropy AS scars_delta_entropy, scars.cls_angle AS scars_cls_angle, scars.semantic_polarity AS scars_semantic_polarity, scars.mutation_frequency AS scars_mutation_frequency, scars.weight AS scars_weight, scars.last_accessed AS scars_last_accessed, scars.scar_vector AS scars_scar_vector, scars.vault_id AS scars_vault_id \nFROM scars \nWHERE scars.vault_id = ?) AS anon_1]\n[parameters: ('vault_a',)]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_ad1f7196', '[\"GEOID_f2f52acb\", \"GEOID_de1d0470\"]', 'auto-cycle', '2025-06-11 10:00:24.108486', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 10:00:24.153771', '[0.5803921568627451, 0.5607843137254902, 0.1607843137254902, 0.5215686274509804, 0.043137254901960784, 0.1607843137254902, 0.6745098039215687, 0.4196 ... (7178 characters truncated) ... 392156862745098, 0.2901960784313726, 0.44313725490196076, 0.40784313725490196, 0.4, 0.7294117647058823, 0.6745098039215687, 0.06666666666666667, 0.4]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "cognitive_cycle: (sqlite3.IntegrityError) UNIQUE constraint failed: scars.scar_id\n[SQL: INSERT INTO scars (scar_id, geoids, reason, timestamp, resolved_by, pre_entropy, post_entropy, delta_entropy, cls_angle, semantic_polarity, mutation_frequency, weight, last_accessed, scar_vector, vault_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('SCAR_76f1322b', '[\"GEOID_30e32539\", \"GEOID_e16aa477\"]', 'auto-cycle', '2025-06-11 10:08:35.113290', 'KimeraCognitiveCycle', 0.0, 0.0, 0.0, 120.0, 0.0, 0.6666666666666666, 1.0, '2025-06-11 10:08:35.156845', '[0.11764705882352941, 0.24313725490196078, 0.13725490196078433, 0.6705882352941176, 0.10196078431372549, 0.32941176470588235, 0.7215686274509804, 0.5 ... (7334 characters truncated) ... 90196078, 0.00392156862745098, 0.5176470588235295, 0.9764705882352941, 0.9490196078431372, 0.6745098039215687, 0.6980392156862745, 0.596078431372549]', 'vault_a')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)",
    "vault_operations: Instance <ScarDB at 0x22328d21d30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22328d22cf0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767c9f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767e430> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767fbd0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327eddd30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edf690> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edeb30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edc130> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767ea50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767cf30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de8ad0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22328d22970> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767e5f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767faf0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edd630> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327dea190> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327deb3f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327deaeb0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edef90> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edf770> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edd550> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767c4b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de4f30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edfe70> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767c830> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x222fd82d9b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327debaf0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x222f9540830> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de9e10> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327deb770> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767e890> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767f930> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edde10> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22328d22a50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edf230> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767fe70> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327dea5f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de4750> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de7070> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de7cb0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de8ad0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327deb770> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767c9f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327eddb70> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767e6d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327dea510> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de8ad0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edeb30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de7770> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df43d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de75b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de4e50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de9710> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767f150> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df50f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df7690> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767f150> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de8ad0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edd0f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e18210> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e19b70> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de6510> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edeeb0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de91d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df5e10> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e18f30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e042f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df4e50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de91d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edfa10> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e04f30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e06890> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327edc750> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327deb770> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x2232767edd0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e19550> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e05b70> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e07af0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de89f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e1a350> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x222fd82f310> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e07150> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e24670> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e06510> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327de5c50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e19c50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327dea350> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e24c90> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e273f0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e04910> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e07070> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e19c50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e1ac10> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df7930> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e1add0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e19630> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327e06970> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x222fd82d9b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)",
    "vault_operations: Instance <ScarDB at 0x22327df51d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)"
  ]
}